  language: python
  
  branches:
    only:
      - develop

  python:
    - "3.6"

  before_install:
    - cd API

  install:
    - pip install -r requirements.txt
  
  env: 
    - export APP_SETTINGS='testing'
    - export SECRET='I\xb4\x14\xa6\xb2b\xc41SP\xe7\xd5\xd9\x89\xd0\xd7'
  script:
    - pytest

  

  